### PR TITLE
Add lockfile and refresh dist

### PR DESCRIPTION
**Pull request by legobeat**
using:

  node v8.17.0
  npm v6.13.4

### CODE REVIEW

**Review by mcmire — COMMENTED** [review]
Are these changes tied to each other or are they part of a more general "get this package up to date" suite of changes?

**Comment by legobeat** [comment]
@mcmire I don't recall if there is also a specific issue which this also addresses, but this is one of the leafs involved in getting the `ethjs-` dependency subtrees deduped, secure, manageable, and ultimately easier to replace if desired. At the very least, consolidating ethereum provider (making any remaning `ethjs` package(s) use our generic provider and eventually fully deprecate `ethjs-provider-http`). Regardless of if and how we get there, this  is part of the story of making that transition safe (lockfile addition; having built dist actually match the source version).

There has been one release made, but not yet used, so far:
- https://github.com/MetaMask/ethjs-rpc

Related repos. Most of these are ultimately depending on this package: 
- https://github.com/MetaMask/ethjs-query
- https://github.com/MetaMask/ethjs-filter
- https://github.com/MetaMask/ethjs-util
- https://github.com/MetaMask/ethjs
- https://github.com/MetaMask/ethjs-abi
- https://github.com/MetaMask/ethjs-contract
- https://github.com/MetaMask/ethjs-format
- https://github.com/MetaMask/ethjs-schema
- https://github.com/MetaMask/ethjs-unit

Note that AFAIK, MetaMask is not currently using these forks yet for product, while original author has communicated that they are no longer interested in maintaining these packages.

So this would be one of the first steps in improving on the situation.

**Comment by mcmire** [comment]
@legobeat Cool. Thanks for the context!

**Review by mcmire — APPROVED** [review]
Looks good!

**Pull request merged**
