### PR TITLE
bump devDependencies

### PR DESCRIPTION
**Pull request by legobeat**
- Bump and unpin devDependencies while keeping backwards-compatibility with runtime
- Update from webpack 2 to webpack 3
- Update from babel 6 to babel 7
  - BREAKING: Add peerDependency `@babel/runtime@^7.0.0`

### CODE REVIEW

**Comment by legobeat** [comment]
@SocketSecurity ignore update-browserslist-db@1.0.13

shell access ok

**Comment by legobeat** [comment]
@SocketSecurity ignore rxjs@6.6.7

network access ok

**Comment by legobeat** [comment]
@SocketSecurity ignore @nicolo-ribaudo/eslint-scope-5-internals@5.1.1-v1
    @SocketSecurity ignore eslint-module-utils@2.8.0
    @SocketSecurity ignore os-browserify@0.3.0
    @SocketSecurity ignore pathval@1.1.1
    @SocketSecurity ignore is-async-function@2.0.0
    @SocketSecurity ignore anymatch@3.1.3
    @SocketSecurity ignore convert-source-map@2.0.0
    @SocketSecurity ignore unicode-canonical-property-names-ecmascript@2.0.0
    @SocketSecurity ignore unicode-match-property-ecmascript@2.0.0
    @SocketSecurity ignore align-text@0.1.4
    @SocketSecurity ignore loupe@2.3.7
    @SocketSecurity ignore ms@2.1.2
    @SocketSecurity ignore check-error@1.0.3
    @SocketSecurity ignore browserify-zlib@0.2.0
    @SocketSecurity ignore wordwrap@0.0.2

authors, no readme ok

**Comment by legobeat** [comment]
@SocketSecurity ignore fsevents@2.1.3

deprecated, via mocha

**Comment by legobeat** [comment]
@SocketSecurity ignore yargs-parser@7.0.0

not directly impacting; existing version of dependency also affected

**Comment by legobeat** [comment]
@SocketSecurity ignore mem@1.1.0

**Review by Mrtenz — APPROVED** [review]

**Pull request merged**
